### PR TITLE
Update Metadata İnfo! Rainbow Xrc20 Token

### PR DESCRIPTION
**Pull request by rainbowIotx**
,
  "io18d6759s7k4pgw842844vf9uktrcvfjdwekw9ea": {
    "name": "Rainbow",
    "description": "Rainbow is a Smart decentralized token builds on XRC20",
    "logo": "io18d6759s7k4pgw842844vf9uktrcvfjdwekw9ea.png",
    "type": "xrc20",
    "symbol": "RAIN",
    "decimals": 8
  }
io18d6759s7k4pgw842844vf9uktrcvfjdwekw9ea

Twitter Page:

https://twitter.com/RainbowXrc20

WebSite:

https://www.rain-bow.xyz

### CODE REVIEW

**Comment by guo** [comment]
Hello, thanks for your submission. Your website is down. Could you please briefly explain what the token is fo?

Thanks

**Comment by rainbowIotx** [comment]
> Hello, thanks for your submission. Your website is down. Could you please briefly explain what the token is fo?
> 
> Thanks

WebSite now is Run. You Can check sir

**Comment by rainbowIotx** [comment]
> Hello, thanks for your submission. Your website is down. Could you please briefly explain what the token is fo?
> 
> Thanks

We have now added some basic information to our website. I noticed that there is no Nft Marketplace in Iotex Dapps yet. Later, if Iotex really accepts us, we have an Iotex / Rainbow Nft marketplace plan.

**Comment by rainbowIotx** [comment]
> Hello, thanks for your submission. Your website is down. Could you please briefly explain what the token is fo?
> 
> Thanks

As Rainbow, our aim is to create a quality project that moves slowly and surely instead of being a fast / poor quality project. For example, we will not add large amounts to the liquidity pool at once. We will gradually increase our liquidity pool as our project evaluates and develops over time. We will prove to people how big things can be achieved with small things. This way we will show our quality.

**Comment by guo** [comment]
accepted and merged. We highly recommend you create a telegram group so people can connect with you there. Thanks!

**Comment by rainbowIotx** [comment]
> accepted and merged. We highly recommend you create a telegram group so people can connect with you there. Thanks!

Thank You so Much... :)
And Rainbow Telegram Group is Opened
https://t.me/RainbowXrc20

**Comment by devilschalice** [comment]
Hello, how are we doing the application? How can I add metadata? Can I get information?

**Pull request merged**
