### PR TITLE
Update token-metadata.json

### PR DESCRIPTION
**Pull request by excelliumCoin**

### CODE REVIEW

**Comment by guo** [comment]
Please add the logo file. 

also please include project website and team etc.

Thanks!

**Comment by bob9090** [comment]
"io1fs9py0ck0e8jjyl0eh7sqj56r0knaswd0s746d": {
    "name": "BOB",
    "description": "BOB is a decentralized token builds on IoTeX blockchain  ",
    "logo": "bob.png",
    "type": "xrc20",
    "symbol": "bob"
    "decimals": 18
  }

bob

social network 
https://www.reddit.com/r/BOBcrypto/
https://twitter.com/BOBcryptoIOT

**Comment by guo** [comment]
please fix the unit test. You may have missed your logo file

**Comment by guo** [comment]
There are multiple PR about this tokens. Could you please close all them and create a clean one?  The PR needs to be 
1. unit tested (passing the unit test to ensure the format is correct)
2. with website including the purpose of token, how to use the token etc.
3. social profile.

Thanks!

**Comment by bob9090** [comment]
Hello sir, we have open a new PR

https://github.com/iotexproject/iotex-token-metadata/pull/28

**Pull request closed without merging**
