### PR TITLE
IoTeXjr project

### PR DESCRIPTION
**Pull request by Ecream**
…n-metadata.json

### CODE REVIEW

**Comment by guo** [comment]
could you please add public information like website, twitter, etc.?

**Comment by Ecream** [comment]
You can reach our twitter account with that link https://twitter.com/Iotexjr?s=09. Is ıt enough or I have to add this somewhere in metadata.

**Comment by guo** [comment]
Do you have a website with more information about the token? like purpose, usage, etc.

**Comment by Ecream** [comment]
The website is at the establishment stage and most of the setup is complete.  In line with the demands of our community, we need to add a picture to our token as soon as possible. If the website has to be established for this request, we can launch the website as soon as possible, even if it is not exactly what we want, but this will damage our reputation.

**Comment by Ecream** [comment]
https://www.iotexjr.com

**Comment by guo** [comment]
good. but it seems you are using IoTeX's intro video on your website. that's highly not recommended.

**Comment by guo** [comment]
please update the title of the PR as well.

**Comment by Ecream** [comment]
We delete the Iotex ıntro video on our website and also the title of the PR changed. Thanks.

**Comment by Ecream** [comment]
Hi, Mr Guo we are still for waiting. We have to start our project immediately.

**Comment by guo** [comment]
no update. closing now.

**Pull request closed without merging**
