### PR TITLE
The Iotexsons

### PR DESCRIPTION
**Pull request by Iotexsons**
## Token Information

- **Project official website**: https://iotexsons.io

- **Project official social**: https://twitter.com/theiotexsons?s=21 / https://t.me/iotexsons

## Verification of Token

- [✅] verify of your token smart contract on iotexscan. io12h9u098h2alr66mc0sq55cru8ymnvvhtgnx4sv / io1hej3flz2wqne8er0udgkl3cdzcx38frrqs7pwt
- [✅] add your token address to your website and list here: https://iotexscout.io/address/0x55cbc794f7577e3d6b787c014a607c39373632eb#code / https://iotexscout.io/address/0xbe6514fc4a702793e46fe3516fc70d160d13a463#code

### CODE REVIEW

**Review by ququzone — COMMENTED** [review]
Need add your token address to your website.

**Review by ququzone — COMMENTED** [review]
Contract `io1qp6djyvndp3sksjevsw4aa7h6m79n2eyq46gra` also needs to verify code.

**Comment by Iotexsons** [comment]
Hello, I have deleted the token metadata in the meantime. Since this was not created with Remix but with the Dapp MintToken in IoPay. 

I have added our contract data to our website /Home below.

**Comment by Iotexsons** [comment]
Hello PNG file has been deleted. @ququzone

**Review by ququzone — APPROVED** [review]

**Pull request merged**
