### PR TITLE
new token token-metadata.json

### PR DESCRIPTION
**Pull request by bob9090**
"io1fs9py0ck0e8jjyl0eh7sqj56r0knaswd0s746d": {
    "name": "BOB",
    "description": "BOB is a decentralized token builds on IoTeX blockchain  ",
    "logo": "bob.png",
    "type": "xrc20",
    "symbol": "bob"
    "decimals": 18
  }
https://www.reddit.com/r/BOBcrypto/
https://twitter.com/BOBcryptoIOT
bob

### CODE REVIEW

**Comment by guo** [comment]
do you have a website with project description and/or team?

**Comment by guo** [comment]
please also resolve the conflicts too. Thanks!

**Comment by bob9090** [comment]
I do not have a website but I have a team and a community on Reddit 

Envoyé de mon iPhone

**Comment by bob9090** [comment]
Our website 

https://bobcrypto.weebly.com/

Envoyé de mon iPhone

**Comment by bob9090** [comment]
Our website is https://www.bob-crypto.com

**Pull request closed without merging**
