### PR TITLE
add MIST token

### PR DESCRIPTION
**Pull request by alchemlstcoin**
- **Project official website**: https://alchemist.farm/

- **Project official social**: https://twitter.com/_alchemistcoin

### CODE REVIEW

**Comment by alchemlstcoin** [comment]
@guo Could you review my withdrawal request about my Alchemis token (MIST) thank you.

**Comment by guo** [comment]
the website does not load. Could you please take a look?

**Comment by guo** [comment]
also, unit test did not pass.

**Comment by alchemlstcoin** [comment]
the link is working. You can rectify, thank you very much.

**Comment by alchemlstcoin** [comment]
@guo asks me for approval for the workflow

**Pull request closed without merging**
